# Generated by Django 5.2.16 on 2026-07-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('state', models.CharField(choices=[('RECRUITING', 'Recruiting'), ('IN_PROGRESS', 'In Progress'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='RECRUITING', max_length=15)),
                ('termination_reason', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('TEAM_ISSUES', 'Team Issues'), ('TEAM_FAILURE', 'Team Failure'), ('PM_CANCELED', 'Pm Canceled'), ('OTHER', 'Other')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
                ('capacity', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectrole')),
            ],
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('project_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projectrole')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_required_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], max_length=15)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='skills.skill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'TERMINATED'), ('termination_reason__isnull', False)), models.Q(models.Q(('state', 'TERMINATED'), _negated=True), ('termination_reason__isnull', True)), _connector='OR'), name='chk_termination_reason'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project_role', 'member_status'], name='projects_pr_project_d14fdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member_pk'),
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(fields=('role', 'skill'), name='unique_role_skill_pk'),
        ),
    ]
