# Generated by Django 5.2.16 on 2026-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_backfill_pm_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='visible_on_profile',
            field=models.BooleanField(default=True),
        ),
    ]
