# Generated by Django 5.2.16 on 2026-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
