# Generated by Django 5.2.16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('AD', 'Ad'), ('CANDIDATE', 'Candidate')], max_length=10)),
                ('target_id', models.PositiveIntegerField()),
                ('vote', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recommendation_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('min_match_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_by_recommendation_preferences', to='skills.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('USER', 'User'), ('PROJECT', 'Project'), ('JOB_AD', 'Job Ad')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('is_query', models.BooleanField()),
                ('text_hash', models.CharField(max_length=64)),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['recommendation_type', 'target_id'], name='recommenda_recomme_1b1e6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'recommendation_type', 'target_id'), name='unique_feedback_per_user_target'),
        ),
        migrations.AddConstraint(
            model_name='recommendationpreference',
            constraint=models.CheckConstraint(check=models.Q(('min_match_score__gte', 0.0), ('min_match_score__lte', 1.0)), name='chk_min_match_score_range'),
        ),
        migrations.AddIndex(
            model_name='embeddingcache',
            index=models.Index(fields=['object_type', 'object_id'], name='recommenda_object__7d6d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='embeddingcache',
            constraint=models.UniqueConstraint(fields=('object_type', 'object_id', 'is_query'), name='unique_embedding_per_object_direction'),
        ),
    ]
