# Generated by Django 5.2.16 on 2026-07-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='embeddingcache',
            new_name='recommendat_object__25a319_idx',
            old_name='recommenda_object__7d6d1a_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationfeedback',
            new_name='recommendat_recomme_95bdba_idx',
            old_name='recommenda_recomme_1b1e6a_idx',
        ),
    ]
