# Generated by Django 5.2.16 on 2026-07-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('COLLAB_REQUEST', 'Collab Request'), ('INVITATION', 'Invitation'), ('RESIGNATION', 'Resignation')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_FEEDBACK', 'Pending Feedback'), ('WAITING_FOR_US', 'Waiting For Us'), ('CLOSED_ACCEPTED', 'Closed Accepted'), ('CLOSED_REJECTED', 'Closed Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_FEEDBACK', max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('project_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectrole')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_tickets', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
